/** Presentation-only translations. Never translate keys, enum payloads or user text. */
const labels: Record<string, string> = {
  'Icon Key': '图标引用键',
  Mana: '法力',
  Cooldown: '冷却',
  Material: '材质',
  Data: '数据值',
  Type: '类型',
  'Min Distance': '最小距离',
  'Target Caster': '以施法者为目标',
  'Min Damage': '最小伤害',
  'Max Damage': '最大伤害',
  Category: '类别',
  Lore: '物品描述',
  Radius: '半径',
  Group: '目标阵营',
  'Through Wall': '穿墙',
  'Include Caster': '包含施法者',
  'Max Targets': '最大目标数',
  Random: '随机',
  Range: '范围',
  Angle: '角度',
  Tolerance: '容差',
  'Ground Only': '仅地面',
  Forward: '前方',
  Upward: '上方',
  Right: '右方',
  Key: '引用键',
  Armor: '护甲',
  'Check Material': '检查材质',
  'Check Data': '检查数据',
  'Check Lore': '检查描述',
  'Check Name': '检查名称',
  Name: '名称',
  Regex: '正则表达式',
  Attribute: '属性',
  Min: '最小值',
  Max: '最大值',
  Biome: '生物群系',
  Distance: '距离',
  'At least': '至少',
  Chance: '概率',
  Class: '职业',
  Exact: '精确匹配',
  'Min Level': '最低等级',
  'Max Level': '最高等级',
  'In Combat': '战斗中',
  Seconds: '秒数',
  Crouching: '下蹲',
  Direction: '方向',
  'Min Value': '最小值',
  'Max Value': '最大值',
  Types: '类型列表',
  Amount: '数量',
  'Min Light': '最低亮度',
  'Max Light': '最高亮度',
  'Contains Text': '包含文本',
  Text: '文本',
  Permission: '权限',
  Potion: '药水效果',
  'Min Rank': '最低阶级',
  'Max Rank': '最高阶级',
  Skill: '技能',
  'Slots (one per line)': '槽位列表',
  Status: '状态',
  Time: '时间',
  Tool: '工具',
  State: '状态',
  'Counts as Cast': '计为技能施放',
  Slot: '槽位',
  Durability: '耐久度',
  Custom: '自定义',
  Overwrite: '覆盖',
  'Armor Stand Key': '盔甲架引用键',
  Duration: '持续时间',
  'Name visible': '显示名称',
  'Follow target': '跟随目标',
  'Apply gravity': '受重力影响',
  Small: '小型',
  'Show arms': '显示手臂',
  'Show base plate': '显示底座',
  Visible: '可见',
  Marker: '标记实体',
  'Forward Offset': '前方偏移',
  'Upward Offset': '上方偏移',
  'Right Offset': '右方偏移',
  'Skills 一行一个': '技能列表',
  Head: '头部',
  Body: '身体',
  'Left Arm': '左臂',
  'Right Arm': '右臂',
  'Left Leg': '左腿',
  'Right Leg': '右腿',
  Stackable: '可叠加',
  Shape: '形状',
  Block: '方块',
  'Block Data': '方块数据',
  'Width (X)': '宽度（X）',
  'Height (Y)': '高度（Y）',
  'Depth (Z)': '深度（Z）',
  Immediate: '立即执行',
  Modifier: '修饰方式',
  Value: '数值',
  Still: '仍然生效',
  Command: '命令',
  'Execute Type': '执行方式',
  'Skill (or "all")': '技能（all 表示全部）',
  'True Damage': '真实伤害',
  Classifier: '伤害分类',
  'Apply Knockback': '施加击退',
  'Skill Damage': '技能伤害',
  Hand: '手持位置',
  Multiplier: '倍率',
  'Skill Defense': '技能防御',
  Delay: '延迟',
  Mob: '生物',
  Adult: '成年',
  Player: '玩家',
  Misc: '其他实体',
  Offhand: '副手',
  Power: '强度',
  'Damage Blocks': '破坏方块',
  Fire: '火焰',
  Food: '饥饿度',
  Saturation: '饱和度',
  Health: '生命值',
  Item: '物品',
  'Item Data': '物品数据',
  Spread: '散布',
  Velocity: '速度',
  Position: '位置',
  Height: '高度',
  'Use Effect': '启用特效',
  'Effect Key': '特效引用键',
  'Shape Direction': '形状平面',
  'Shape Size': '形状大小',
  Animation: '动画',
  'Animation Direction': '动画平面',
  'Animation Size': '动画大小',
  Interval: '间隔',
  'View Range': '可见范围',
  Particle: '粒子',
  DX: 'X 偏移',
  DY: 'Y 偏移',
  DZ: 'Z 偏移',
  Speed: '速度',
  '[PREM] Relative': '相对方向',
  'Forward Speed': '前方速度',
  'Upward Speed': '上方速度',
  'Right Speed': '右方速度',
  Damage: '伤害',
  Message: '消息',
  Arrangement: '排列方式',
  'Circle Direction': '圆形平面',
  'Effect Data': '特效数据',
  'Visible Radius': '可见半径',
  'Packet Amount': '每点粒子数',
  ArmorStand: '盔甲架',
  Steps: '步数',
  Frequency: '频率',
  'Start Angle': '起始角度',
  'H-Translation': '水平平移',
  'V-Translation': '垂直平移',
  'H-Cycles': '水平周期数',
  'V-Cycles': '垂直周期数',
  Gravity: '重力',
  Pierce: '穿透',
  Lifespan: '存活时间',
  'Ambient Particles': '环境粒子',
  Tier: '阶级',
  Linger: '滞留',
  Projectile: '投射物',
  Flaming: '燃烧',
  Cost: '消耗',
  Source: '来源',
  Repetitions: '重复次数',
  Period: '周期',
  'Stop on Fail': '失败时停止',
  Sound: '音效',
  Volume: '音量',
  Pitch: '音调',
  Trigger: '触发器',
  Once: '仅一次',
  'Target Listen Target': '监听对象作为目标',
  Destination: '目标位置',
  'To target': '朝向目标',
  Placeholder: '占位符',
  'Through Walls': '穿墙',
  'World (or "current")': '世界（current 表示当前）',
  X: 'X 坐标',
  Y: 'Y 坐标',
  Z: 'Z 坐标',
  Yaw: '偏航角',
  'Only Horizontal': '仅水平方向',
  'Collar Color': '项圈颜色',
  'Wolf Name': '狼的名称',
  Sitting: '坐下',
  'Skills (one per line)': '技能列表',
  Tick: '刻数',
  Action: '动作',
  SkillName: '技能名称',
  ID: '标识',
};

/** Unknown plugin captions are retained; built-in English captions have full coverage tests. */
export function fieldLabel(label: string): string {
  return labels[label] ?? label;
}

/** Human-readable enum captions do not change the English option value. */
export function optionLabel(value: string): string {
  return (
    (
      {
        True: '是',
        False: '否',
        Any: '任意',
        All: '全部',
        None: '无',
        Ally: '友方',
        Enemy: '敌方',
        Both: '两者',
        'Percent Left': '剩余生命百分比',
        'Percent Missing': '损失生命百分比',
        Circle: '圆形',
        Hemisphere: '半球',
        Sphere: '球形',
        'Start Crouching': '开始下蹲',
        'Stop Crouching': '停止下蹲',
      } as Record<string, string>
    )[value] ??
    labels[value] ??
    `选项：${value}`
  );
}
