/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    // Shadow 9.x supports Gradle 9; 8.1.1 still accesses the removed
    // CopyDetails.mode property and fails while writing META-INF.
    id("com.gradleup.shadow") version "9.2.2"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.aliyun.com/repository/public")
        metadataSources {
            mavenPom()
            artifact()
            ignoreGradleMetadataRedirection()
        }
    }

    maven {
        url = uri("https://mirrors.tuna.tsinghua.edu.cn/maven2/")
        metadataSources {
            mavenPom()
            artifact()
            ignoreGradleMetadataRedirection()
        }
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
        // Paper 26.2 publishes Gradle metadata with a Java 25 variant. The
        // plugin compiles on Java 25 but targets Java 8, so use its Maven POM
        // here to avoid Gradle rejecting the API as an incompatible variant.
        metadataSources {
            mavenPom()
            artifact()
            ignoreGradleMetadataRedirection()
        }
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.md-5.net/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://mvn.lumine.io/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://repo.dmulloy2.net/nexus/repository/public/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://repo.md-5.net/content/groups/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
        metadataSources {
            mavenPom()
            artifact()
            ignoreGradleMetadataRedirection()
        }
    }
    maven {
        name = "CodeMC"
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }
}

// Compile-only Paper API. See gradle.properties for why this is the newest
// API rather than the oldest supported server.
val paperApi = "io.papermc.paper:paper-api:${property("paperApiVersion")}"

dependencies {
    // Cross-version material and item NBT support used by non-player items.
    implementation("com.github.cryptomorin:XSeries:13.7.1")
    implementation("de.tr7zw:item-nbt-api:2.15.5")
    compileOnly(paperApi)
    implementation(project(":root:compat:bukkit-api"))
    implementation(project(":root:serialization:serialization-api"))
    implementation(project(":root:serialization:serialization-gson"))
    implementation(project(":root:serialization:serialization-legacy-nbt"))
    // One NMS module per generation. The newest is enough at compile time
    // because each generation extends the one below it.
    implementation(project(":root:nms:nms-api"))
    implementation(project(":root:nms:nms-v1_12"))
    implementation(project(":root:nms:nms-v26_1"))
    implementation(project(":root:nms:nms-v26_2"))
    implementation(project(":root:storage:storage-api"))
    implementation(project(":root:storage:storage-sqlite"))
    implementation(project(":root:storage:storage-sql"))
    // MythicMobs 适配层。主工程只依赖接口，v4/v5 实现在运行时按版本反射加载，
    // 因此主工程编译期不会接触任何 MythicMobs 类型。
    implementation(project(":root:mythic"))
    compileOnly("io.netty:netty-all:4.1.51.Final")
    compileOnly("net.md-5:bungeecord-api:1.16-R0.1") {
        // Brigadier is not referenced by this plugin and the old snapshot is unavailable.
        exclude(group = "net.md-5", module = "brigadier")
    }
    compileOnly("org.projectlombok:lombok:1.18.30")
    compileOnly("fr.neatmonster:nocheatplus:3.16.1-SNAPSHOT")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7")
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.0.3")
    compileOnly("com.sk89q.worldedit:worldedit-core:7.1.0")
    compileOnly(fileTree("lib"))
}

group = "com.sucy.skill"
version = "R-1.2.20"
// 子项目名为 root，若不固定 archivesName 产物会变成 root-R-1.2.15.jar。
base.archivesName.set("ProSkillAPI")
description = "ProSkillAPI"
java.sourceCompatibility = JavaVersion.VERSION_1_8
java.targetCompatibility = JavaVersion.VERSION_1_8

java {
    // Gradle itself runs with the modern toolchain, while --release below keeps
    // the generated plugin classes loadable on Java 8 server environments.
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

tasks.withType<JavaCompile>() {
    // The Gradle daemon may run on Java 25/26, but plugin classes must stay
    // Java 8-compatible for older Minecraft server runtimes.
    options.release.set(8)
    options.encoding = "UTF-8"
    // JDK 25 warns about the Java-8 target and Bukkit's legacy APIs that are
    // intentionally required for the 1.12.2 compatibility contract. These
    // flags silence compatibility noise while leaving ordinary compiler errors
    // and unchecked warnings visible.
    options.compilerArgs.addAll(listOf("-Xlint:-options", "-Xlint:-removal"))
}

subprojects {
    apply(plugin = "java")

    repositories {
        mavenLocal()
        maven {
            url = uri("https://maven.aliyun.com/repository/public")
            metadataSources {
                mavenPom()
                artifact()
                ignoreGradleMetadataRedirection()
            }
        }
        maven {
            url = uri("https://mirrors.tuna.tsinghua.edu.cn/maven2/")
            metadataSources {
                mavenPom()
                artifact()
                ignoreGradleMetadataRedirection()
            }
        }
        maven {
            url = uri("https://repo.papermc.io/repository/maven-public/")
            metadataSources {
                mavenPom()
                artifact()
                ignoreGradleMetadataRedirection()
            }
        }
        maven {
            url = uri("https://repo.maven.apache.org/maven2/")
            metadataSources {
                mavenPom()
                artifact()
                ignoreGradleMetadataRedirection()
            }
        }
    }

    dependencies {
        "compileOnly"(paperApi)
        "compileOnly"("io.netty:netty-all:4.1.51.Final")
        "compileOnly"("net.md-5:bungeecord-api:1.16-R0.1") {
            exclude(group = "net.md-5", module = "brigadier")
        }
    }

    extensions.configure<JavaPluginExtension> {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(25))
        }
    }

    tasks.withType<JavaCompile>() {
        // Keep NMS modules on the same Java 8 bytecode contract as the plugin jar.
        options.release.set(8)
        options.encoding = "UTF-8"
        options.compilerArgs.addAll(listOf("-Xlint:-options", "-Xlint:-removal"))
    }
}

/**
 * Modules that must always be present at runtime.
 *
 * Every NMS generation is folded in, not just the newest: which one is used is
 * a runtime decision made by NmsProvider against the running core, so shipping
 * a subset would silently drop support for the versions left out.
 */
val bundledModules = listOf(
    ":root:compat:bukkit-api",
    ":root:serialization:serialization-api",
    ":root:serialization:serialization-gson",
    ":root:serialization:serialization-legacy-nbt",
    ":root:nms:nms-api",
    ":root:nms:nms-v1_8",
    ":root:nms:nms-v1_9",
    ":root:nms:nms-v1_10",
    ":root:nms:nms-v1_11",
    ":root:nms:nms-v1_12",
    ":root:nms:nms-v1_13",
    ":root:nms:nms-v1_16",
    ":root:nms:nms-v1_17",
    ":root:nms:nms-v1_20",
    ":root:nms:nms-v1_21",
    ":root:nms:nms-v26_1",
    ":root:nms:nms-v26_2",
    ":root:storage:storage-api",
    ":root:storage:storage-sqlite",
    ":root:storage:storage-sql",
    // MythicMobs 适配：接口层与两个大版本的实现，运行时按探测结果择一使用。
    ":root:mythic",
    ":root:mythic:v4",
    ":root:mythic:v5"
)

/**
 * Third-party libraries with no server-provided equivalent.
 *
 * Optional server APIs stay compileOnly and are deliberately absent here.
 */
val shadedLibraryPrefixes = listOf(
    "gson-",
    "sqlite-jdbc-",
    "HikariCP-",
    "mysql-connector-j-",
    "postgresql-",
    "checker-qual-"
)

/**
 * Optional integrations, each shipped as its own artifact.
 *
 * These are genuinely optional: they are not in the main jar at all, so a
 * server without the corresponding plugin does not carry their classes.
 * ModuleBootstrap discovers whichever ones the administrator dropped in, which
 * is what makes "enabled according to what is installed" true of the
 * distribution and not only of the code path.
 *
 * Add `-Pbundle.integrations=true` to fold them into the main jar instead, for
 * distributions that prefer a single file.
 */
val optionalIntegrations = listOf(":root:integration:dragoncore")

val bundleIntegrations = (findProperty("bundle.integrations") as String?)?.toBoolean() ?: false

tasks.jar {
    // The embedded module jars must be built before their contents are copied;
    // otherwise Gradle can produce a successful but incomplete plugin jar.
    dependsOn(bundledModules.map { project(it).tasks.named("classes") })
    // Required modules are folded in so administrators still deploy one jar
    // while the source tree keeps versioned concerns isolated.
    bundledModules.forEach { path ->
        // Consume compiled classes directly. Some optional modules have
        // compileOnly server APIs, so relying on runtimeClasspath silently
        // omits their implementations from the distributable jar.
        from(project(path).sourceSets.main.get().output)
    }
    if (bundleIntegrations) {
        optionalIntegrations.forEach { path ->
            from(project(path).tasks.named("jar").map { zipTree(it.outputs.files.singleFile) })
        }
    }
    from(configurations.runtimeClasspath.get()
            .filter { artifact -> shadedLibraryPrefixes.any { artifact.name.startsWith(it) } }
            .map { zipTree(it) })
    exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.shadowJar {
    archiveClassifier.set("")
    configurations = listOf(project.configurations.runtimeClasspath.get())
    // shadowJar does not inherit custom inputs from jar; repeat the embedded
    // module outputs so the release artifact contains every implementation.
    bundledModules.forEach { path ->
        from(project(path).sourceSets.main.get().output)
    }
    relocate("com.cryptomorin.xseries", "com.sucy.skill.libs.xseries")
    relocate("de.tr7zw.changeme.nbtapi", "com.sucy.skill.libs.nbtapi")
}

tasks.assemble {
    dependsOn(tasks.shadowJar)
}

/**
 * Builds the optional integration jars alongside the plugin jar so a release
 * ships them as separate, droppable artifacts.
 */
val integrationJars by tasks.registering(Copy::class) {
    description = "Collects optional integration module jars into build/integrations"
    group = "build"
    optionalIntegrations.forEach { path ->
        from(project(path).tasks.named("jar"))
    }
    into(layout.buildDirectory.dir("integrations"))
}

tasks.named("assemble") {
    dependsOn(integrationJars)
}
