name: Build Artifacts

on:
  push:
    branches:
      - master
    paths:
      - src/main/**/*.java
  pull_request:
    branches:
      - master
    paths:
      - src/main/**/*.java

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package -e
    - uses: actions/upload-artifact@v1
      with:
        name: ProSkillAPI artifact
        path: target/ProSkillAPI-dev-build.jar
